In [1]:
import numpy as np
import pandas as pd

# example 1.1

In [2]:
A=np.array(np.mat('3,0,0;5,1,-1;-2,2,4'))
B=np.array(np.mat('1,0;0,-1;2,3'))
lambda1=np.zeros((3,3))
lambda2=np.zeros((2,2))
np.fill_diagonal(lambda1,(1,0,-1))
np.fill_diagonal(lambda2,(2,-3))


In [3]:
#AB
np.matmul(A,B)

array([[ 3,  0],
       [ 3, -4],
       [ 6, 10]])

In [4]:
#lambda1*B
np.matmul(lambda1,B)

array([[ 1.,  0.],
       [ 0.,  0.],
       [-2., -3.]])

In [5]:
#B*lambda2
np.matmul(B,lambda2)

array([[ 2.,  0.],
       [ 0.,  3.],
       [ 4., -9.]])

In [6]:
one=np.transpose([[1,1,1]])

In [7]:
one

array([[1],
       [1],
       [1]])

In [8]:
np.matmul(np.transpose(one),B)

array([[3, 2]])

In [9]:
one=np.transpose([[1,1]])

In [10]:
np.matmul(B,one)

array([[ 1],
       [-1],
       [ 5]])

# example 1.2

In [11]:
#rank of A
np.linalg.matrix_rank(A)

3

In [12]:
#trace of A
np.diag(A).sum()

8

In [13]:
#determinant of A
int(round(np.linalg.det(A),0))

18

# example 1.3

In [14]:
v,w=np.linalg.eig(A)
v,w

(array([3., 2., 3.]),
 array([[ 0.00000000e+00,  0.00000000e+00,  9.93013661e-17],
        [-4.47213595e-01,  7.07106781e-01,  4.47213595e-01],
        [ 8.94427191e-01, -7.07106781e-01, -8.94427191e-01]]))

In [15]:
# for lambda1=3, algebric multiplicity=2

In [16]:
#geometric multiplicity
np.linalg.matrix_rank(w[:,(0,2)])

1

In [17]:
#for lambda2=2, algebric multiplicity=1

In [18]:
#geometric multiplicity=1

np.linalg.matrix_rank(w[:,1])

1

# example 1.4

In [19]:
v.prod()==int(round(np.linalg.det(A),0))

True

In [20]:
v.sum()==np.diag(A).sum()

True

# example 1.5

In [21]:
A=np.array(np.mat('0,1;3,2'))
A

array([[0, 1],
       [3, 2]])

In [22]:
np.linalg.eig(A)
#A has 2 distinct eigen values as corollary 1.3

(array([-1.,  3.]), array([[-0.70710678, -0.31622777],
        [ 0.70710678, -0.9486833 ]]))

In [23]:
B=np.array(np.mat('0,1;-1,2'))

In [24]:
np.linalg.eig(B)
#B has only 1 distince eigen value therefore B is not diagonalizable

(array([1., 1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

# example 1.6


In [41]:
A=np.array(np.mat('0,2;2,3'))
A

array([[0, 2],
       [2, 3]])

In [42]:
zero_matrix=np.zeros((2,2))

In [72]:
v,w=np.linalg.eig(A)
v,w

(array([-1.,  4.]), array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [44]:
#to prove
np.fill_diagonal(zero_matrix,v)
zero_matrix

array([[-1.,  0.],
       [ 0.,  4.]])

In [45]:
w.dot(zero_matrix).dot(np.transpose(w))
#this is exactly A

array([[0., 2.],
       [2., 3.]])

# example 1.7

In [46]:
v,w=np.linalg.eig(A)

In [49]:
v,w

(array([-1.,  4.]), array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [67]:
A

array([[0, 2],
       [2, 3]])

In [66]:
w

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [60]:
#find corrsponding max eigen value
max_ind=np.where(v==v.max())[0]

In [73]:
-w[:,max_ind]

array([[0.4472136 ],
       [0.89442719]])

# example 1.8

In [35]:
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
A
#this is a symetric matrix 

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [32]:
v,w=np.linalg.eig(A)

In [34]:
v>0

array([ True,  True,  True])

In [ ]:
#All the eigen values are positive, therefore A is positive definite